application/frontend/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, PasswordField, IntegerField, SelectField
from wtforms.validators import DataRequired, EqualTo, Length

class LoginForm(FlaskForm):
	username = StringField("Username", validators=[DataRequired()])
	password = PasswordField("Password", validators=[DataRequired()])

class RegisterForm(FlaskForm):
	username = StringField("Username", validators=[DataRequired()])
	password = PasswordField("Password", validators=[DataRequired(), Length(min=7)])
	confirm = PasswordField("Confirm", validators=[DataRequired(), Length(min=7), EqualTo('password', message="Passwords must match!")])

class SearchForm(FlaskForm):
	SearchBy=[('partnum', 'Part Number'), ('partname', 'Part Name'), ('Vendor', 'Vendor/Supplier')]
	choices = SelectField(u'Search by:', choices=SearchBy, validators=[DataRequired()])
	search = StringField("Find Parts", validators=[DataRequired()])

class CheckoutPart(FlaskForm):
	quantity = IntegerField("Quantity", validators=[DataRequired()])

application/backend/routes.py
from flask import Blueprint, render_template, url_for, request, json, jsonify, redirect, flash, abort
from flask_login import current_user, login_user, logout_user
from application.models import db, User, Part, Tracker
from application import login_manager, app
import uuid
import datetime
import jwt
from .forms import LoginForm, ChangePasswordForm, PartForm, UploadForm
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash
from .upload import allowed_file, upload_file

back = Blueprint('backend', __name__, template_folder='templates')

@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))

def admin_required(f):
	@wraps(f)
	def decorated(*args, **kwargs):
		if current_user.is_authenticated and current_user.admin:
			is_admin = True
		else:
			return redirect(url_for('backend.login'))
		return f(*args, **kwargs)
	return decorated

@back.route('/')
@admin_required
def index():
	return render_template('backend/index.html')

@back.route('/users')
@admin_required
def users():
	users = User.query.all()
	return render_template('backend/users.html', users=users)

@back.route('/inventory')
@admin_required
def inventory():
	parts = Part.query.all()
	return render_template('backend/inventory.html', parts=parts)

@back.route('/report')
@admin_required
def report():
	parts = Part.query.order_by(Part.location).all()
	return render_template('backend/report.html', parts=parts, datenow=datetime.datetime.now())

@back.route('/login', methods=['GET', 'POST'])
def login():
    return redirect(url_for('frontend.login'))

@back.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('backend.login'))

@back.route('/delete/<userid>')
@admin_required
def delete_user(userid):
	user = User.query.filter_by(public_id=userid).first()
	if user:
		db.session.delete(user)
		db.session.commit()
		flash(user.username + " has been deleted")
		return redirect(url_for('backend.users'))


@back.route('/new-part', methods=['GET', 'POST'])
@admin_required
def new_part():
	form = PartForm()
	if form.validate_on_submit():
		part = Part.query.filter_by(partnum=form.partnum.data).first()
		if not part:
			# create part
			part = Part(partnum=form.partnum.data, name=form.name.data, vendor=form.vendor.data, location=form.location.data, desired_qty=int(form.quantity.data*.75), quantity=form.quantity.data, available_qty=form.quantity.data)
			db.session.add(part)
			db.session.commit()
			flash(part.partnum + " has been added")
			return redirect(url_for('backend.inventory'))
		else:
			flash('Part' + part.partnum + " already exists")
	return render_template('backend/newpart.html', form=form)

@back.route('/delete-part/<partid>')
@admin_required
def delete_part(partid):
	part = Part.query.filter_by(id=partid).first()
	if part:
		db.session.delete(part)
		tracker = Tracker.query.filter_by(partid=partid).delete()
		db.session.commit()
		flash("Part " + part.partnum + " has been deleted")
	return redirect(url_for('backend.inventory'))

@back.route('/edit-part/<partid>', methods=['GET','POST'])
@admin_required
def edit_part(partid):
	form = PartForm()
	part = Part.query.filter_by(id=partid).first()
	tracker = Tracker.query.filter_by(partid=partid).all()
	if form.validate_on_submit():
		part.available_qty = form.quantity.data
		if tracker:
			for item in tracker:
				item.partnum = form.partnum.data
				item.partname = form.name.data
				part.available_qty -= item.quantity
		part.partnum = form.partnum.data
		part.name = form.name.data
		part.vendor = form.vendor.data
		part.location = form.location.data
		part.quantity = form.quantity.data
		db.session.commit()
		flash("Part " + part.partnum + " has been updated")
		return redirect(url_for('backend.inventory'))
	return render_template('backend/editpart.html', form=form, part=part)

@back.route('/info/<partid>')
@admin_required
def info(partid):
	part = Part.query.filter_by(id=partid).first()
	tracker = Tracker.query.filter_by(partid=partid).order_by(Tracker.date_out).all()
	return render_template('backend/info.html', part=part, tracker=tracker)

@back.route('/upload/', methods=['GET', 'POST'])
@admin_required
def upload():
	form = UploadForm()
	if form.validate_on_submit():
		#try:
		if not upload_file(request.files):
			flash("Error uploading file")
			return redirect(url_for('backend.upload'))
		flash("Inventory has been updated")
		return redirect(url_for('backend.inventory'))
		#except:
			#flash("Error uploading file")
	return render_template('backend/upload.html', form=form)

@back.route('/changepassword/<userid>', methods=['GET', 'POST'])
@admin_required
def change_pass(userid):
	form = ChangePasswordForm()
	if form.validate_on_submit():
		user = User.query.filter_by(public_id=userid).first()
		if user:
			# create user
			user.password_hash=generate_password_hash(form.password.data)
			db.session.commit()
			flash(user.username + "'s password has been updated")
			return redirect(url_for('backend.users'))
		else:
			flash('User not found')
	else:
		user = User.query.filter_by(public_id=userid).first()
		if user:
			return render_template('backend/changepassword.html', username=user.username, form=form)
		else:
			flash("User not found")
	return redirect(url_for('backend.users'))

@back.route('/makeadmin/<userid>')
@admin_required
def make_admin(userid):
	user = User.query.filter_by(public_id=userid).first()
	if user:
		user.admin = True
		db.session.commit()
		flash(user.username + " is now an administrator")
	return redirect(url_for('backend.users'))

@back.route('/makestandard/<userid>')
@admin_required
def make_standard(userid):
	user = User.query.filter_by(public_id=userid).first()
	if user:
		user.admin = False
		db.session.commit()
		flash(user.username + " is now a standard user")
	return redirect(url_for('backend.users'))

application/frontend/routes.py
from flask import Blueprint, render_template, url_for, request, json, jsonify, redirect, flash, abort
from application.models import db, User, Part, Tracker
from application import login_manager, app
from flask_login import current_user, login_required, login_user, logout_user
from .forms import LoginForm, RegisterForm, SearchForm, CheckoutPart
from werkzeug.security import check_password_hash, generate_password_hash
import uuid
import datetime
import jwt
from functools import wraps

mod = Blueprint('frontend', __name__, template_folder='templates')


@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))

def login_required(f):
	@wraps(f)
	def decorated(*args, **kwargs):
		if current_user.is_authenticated:
			is_logged_in = True
		else:
			return redirect(url_for('frontend.login'))
		return f(*args, **kwargs)
	return decorated

def token_required(f):
	@wraps(f)
	def decorated(*args, **kwargs):
		token = request.args.get('token')
		if not token:
			return jsonify({'message' : 'Token is missing!'}), 401
		try:
			data = jwt.decode(token, app.config['SECRET_KEY'])
		except:
			abort(400)
		return f(*args, **kwargs)
	return decorated

@mod.route('/view/<partid>', methods=['GET','POST'])
@login_required
def view_part(partid):
	form = CheckoutPart()
	part = Part.query.filter_by(partnum=partid).first()
	if form.validate_on_submit():
		if form.quantity.data > part.available_qty:
			flash("Quantity exceeds available!")
		else:
			# check if user already has the same part
			samepart = Tracker.query.filter_by(username=current_user.username,partid=part.id).first()
			if samepart:
				samepart.quantity += form.quantity.data
				part.available_qty -= form.quantity.data
				db.session.commit()
			else:
				mypart = Tracker(username=current_user.username,partid=part.id,quantity=form.quantity.data,date_out=datetime.datetime.now(), partnum=part.partnum,partname=part.name)
				part.available_qty -= form.quantity.data
				db.session.add(mypart)
				db.session.commit()
			return redirect(url_for('frontend.dashboard'))
	if part:
		return render_template('frontend/view.html', part=part, form=form)

@mod.route('/checkin/<partid>', methods=['GET','POST'])
@login_required
def checkin(partid):
	form = CheckoutPart()
	part = Part.query.filter_by(id=partid).first()
	mypart = Tracker.query.filter_by(partid=partid).first()
	if form.validate_on_submit():
		if form.quantity.data > mypart.quantity:
			flash("Quantity exceeds available!")
		else:
			# check if user already has the same part
			if form.quantity.data == mypart.quantity:
				part.available_qty += form.quantity.data
				db.session.delete(mypart)
				db.session.commit()
			else:
				part.available_qty += form.quantity.data
				mypart.quantity -= form.quantity.data
				db.session.commit()
			return redirect(url_for('frontend.index'))
	if part:
		return render_template('frontend/checkin.html', part=part, form=form, mypart=mypart)

@mod.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('frontend.index'))

@mod.route('/browse', methods=['GET','POST'])
@login_required
def browse():
	showResults=0
	results=''
	form = SearchForm()
	#parts = Part.query.all()
	if form.validate_on_submit():
		if form.choices.data == 'partnum':
			results = Part.query.filter(Part.partnum.like("%"+form.search.data+"%")).all()
		if form.choices.data == 'partname':
			results = Part.query.filter(Part.name.like("%"+form.search.data+"%")).all()
		if form.choices.data == 'Vendor':
			results = Part.query.filter(Part.vendor.like("%"+form.search.data+"%")).all()
		showResults=1
	if len(results) > 0:
		return render_template('frontend/browse.html', hasParts=1, form=form, results=results,showResults=showResults)
	return render_template('frontend/browse.html', hasParts=0, form=form, results=results,showResults=showResults)

@mod.route('/dashboard')
@login_required
def dashboard():
	myparts = Tracker.query.filter_by(username=current_user.username).all()
	if myparts:
		return render_template('frontend/index.html', myparts=myparts, hasparts=1)
	myparts=0
	return render_template('frontend/index.html', myparts=0, hasparts=0)


@mod.route('/')
@login_required
def index():
	return redirect(url_for('frontend.browse'))
		
@mod.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.get_by_username(form.username.data)
        if user:
        	if user.check_password(form.password.data):
	            login_user(user)
	            return redirect(request.args.get('next') or url_for('frontend.index'))
        flash('Invalid username and/or password.')
    return render_template('frontend/auth/login.html', form=form)


@mod.route('/register', methods=['GET', 'POST'])
def register():
	form = RegisterForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()
		if not user:
			# create user
			new_user = User(public_id=uuid.uuid4().hex, username=form.username.data, password_hash=generate_password_hash(form.password.data))
			db.session.add(new_user)
			db.session.commit()
			login_user(new_user)
			return redirect(url_for('frontend.index'))
		flash('Username already taken!')
	return render_template('frontend/auth/register.html', form=form)

@mod.route('/account')
@login_required
def myaccount():
	return "This is the account page for: {}".format(current_user.email)

application/frontend/templates/frontend/auth_master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
<link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='frontend/favicons/apple-icon-57x57.png')}}">
<link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='frontend/favicons/apple-icon-60x60.png')}}">
<link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='frontend/favicons/apple-icon-72x72.png')}}">
<link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='frontend/favicons/apple-icon-76x76.png')}}">
<link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='frontend/favicons/apple-icon-114x114.png')}}">
<link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='frontend/favicons/apple-icon-120x120.png')}}">
<link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='frontend/favicons/apple-icon-144x144.png')}}">
<link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='frontend/favicons/apple-icon-152x152.png')}}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='frontend/favicons/apple-icon-180x180.png')}}">
<link rel="icon" type="image/png" sizes="192x192"  href="{{ url_for('static', filename='frontend/favicons/android-icon-192x192.png')}}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='frontend/favicons/favicon-32x32.png')}}">
<link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='frontend/favicons/favicon-96x96.png')}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='frontend/favicons/favicon-16x16.png')}}">
<link rel="manifest" href="{{ url_for('static', filename='frontend/favicons/manifest.json')}}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{{ url_for('static', filename='frontend/favicons/ms-icon-144x144.png')}}">
<meta name="theme-color" content="#ffffff">
    <!-- External CSS libraries -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='frontend/css/bootstrap.css') }}">
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid example5">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
                    <a class="navbar-brand" style="padding:5px;" href="{{ url_for('frontend.index') }}"><img class="img-responsive" style=" width: 128px;" src="{{ url_for('static', filename='frontend/images/logo.png')}}" alt="Dispute Bills">Instrumentation Parts Manager   </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}

{% endblock %}

<script src="{{ url_for('static', filename='frontend/js/jquery-2.2.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='frontend/js/bootstrap.min.js') }}"></script>

</body>
</html>

application/frontend/templates/frontend/browse.html
{% extends 'frontend/master.html' %}


{% block title %}
Dashboard - NLMK PartManager
{% endblock %}

{% block content %}

<div class="col-md-1 text-center">

</div>

<div class="col-md-10">

            <div class="well">
                    <p>SEARCH</p>

                                <form enctype="multipart/form-data" method="POST">
                                {{ form.csrf_token }}
                                <div class="form-group">
                                    {{ form.search(class="form-control") }}
                                    {% for error in form.search.errors %}
                                        <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                                                <div class="form-group">
                                    {{ form.choices(class="form-control") }}
                                    {% for error in form.choices.errors %}
                                        <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success btn-lg btn-block"><i class="fas fa-search"></i> Search</button>
                                </div>                  
                                </form>
            </div>

      {% if showResults == 1 %}
      <h3>Search Results</h3>
      {% if hasParts == 1 %}
            <div class="list-group">
        {% for part in results %}
            {% if part.available_qty > 0 %}
                  <a href="{{ url_for('frontend.view_part', partid=part.partnum) }}" class="list-group-item">{{ part.partnum | upper }} {{ part.name | upper }}</a>
            {% else %}
                  <a style="font-color:color.red;" class="list-group-item">{{ part.partnum | upper }} {{ part.name | upper }} <p class="pull-right text-warning">OUT OF STOCK</p></a> 
            {% endif %} 
        {% endfor %}
            </div>
      {% else %}
           <div class="well">
              <p>No results found</p>
            </div>
      {% endif %}
        {% endif %}


{% endblock %}

application/frontend/templates/frontend/checkin.html
{% extends 'frontend/master.html' %}

{% block title %}
{{ part.partnum }} - NLMK PartManager
{% endblock %}


{% block content %}

<!-- Content area start -->
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                    <div class="heading text-center">
                        <h3>{{ part.partnum | upper }} {{ part.name | upper }}</h3>
                    </div>

                            <div class="well">
                                <form method="POST">
                                {{ form.csrf_token }}
                                <p>Total on hand: {{ mypart.quantity }}</p>
                                                            {% with messages = get_flashed_messages() %}
                                  {% if messages %}
                                    {% for message in messages %}
                                      <center><p style="color:red;">{{ message }}</p></center>
                                    {% endfor %}
                                  {% endif %}
                            {% endwith %}
                                <div class="form-group">
                                    {{ form.quantity(class="form-control", placeholder="Qty") }}
                                    {% for error in form.quantity.errors %}
                                        <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success btn-lg btn-block"><i class="fas fa-arrow-circle-right"></i> Return</button>
                                </div>                  
                                </form>
                            </div>



                </div>
                </div>
                <!-- Form content box end -->
            </div>
{% endblock %}

application/frontend/templates/frontend/index.html
{% extends 'frontend/master.html' %}


{% block title %}
Dashboard - NLMK PartManager
{% endblock %}

{% block content %}

<div class="col-md-1 text-center">

</div>

<div class="col-md-10">

      <h3>Your Parts</h3>

{% if hasparts == 1 %}
      <!-- Table -->
      <table class="table table-striped">
    <thead>
        <tr>
            <th>Part #</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Date Out</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
      {% for part in myparts %}
        <tr>
            <td>{{ part.partnum | upper }}</td>
            <td>{{ part.partname | upper }}</td>
            <td>{{ part.quantity | upper  }}</td>
            <td>{{ part.date_out | upper  }}</td>
            <td>
                <a href="{{ url_for('frontend.checkin', partid=part.partid) }}" title="Checkin the part" class="btn btn-sm btn-success"><i class="fas fa-check"></i> Checkin</a>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
           <div class="well">
              <p>No results to display at this time <a href="{{ url_for('frontend.browse') }}" class="btn btn-default">Browse Inventory</a></p>
            </div>
{% endif %}
        
 

        


{% endblock %}

application/frontend/templates/frontend/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

    <!-- External CSS libraries -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='frontend/css/bootstrap.css') }}">
<link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='frontend/favicons/apple-icon-57x57.png')}}">
<link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='frontend/favicons/apple-icon-60x60.png')}}">
<link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='frontend/favicons/apple-icon-72x72.png')}}">
<link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='frontend/favicons/apple-icon-76x76.png')}}">
<link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='frontend/favicons/apple-icon-114x114.png')}}">
<link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='frontend/favicons/apple-icon-120x120.png')}}">
<link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='frontend/favicons/apple-icon-144x144.png')}}">
<link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='frontend/favicons/apple-icon-152x152.png')}}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='frontend/favicons/apple-icon-180x180.png')}}">
<link rel="icon" type="image/png" sizes="192x192"  href="{{ url_for('static', filename='frontend/favicons/android-icon-192x192.png')}}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='frontend/favicons/favicon-32x32.png')}}">
<link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='frontend/favicons/favicon-96x96.png')}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='frontend/favicons/favicon-16x16.png')}}">
<link rel="manifest" href="{{ url_for('static', filename='frontend/favicons/manifest.json')}}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{{ url_for('static', filename='frontend/favicons/ms-icon-144x144.png')}}">
<meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid example5">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="padding:5px;" href="{{ url_for('frontend.index') }}"><img class="img-responsive" style=" width: 128px;" src="{{ url_for('static', filename='frontend/images/logo.png')}}" alt="Dispute Bills">Instrumentation Parts Manager   </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav">
        <li><a href="{{ url_for('frontend.browse') }}"><i class="fas fa-box-open"></i> Browse Inventory</a></li>
        <li><a href="{{ url_for('frontend.dashboard') }}"><i class="fas fa-home"></i> View My Parts</a></li>
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
<form class="navbar-form navbar-left">
<!-- Single button -->
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   <i class="fas fa-user"></i> {{ current_user.username }} <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
     {% if current_user.admin %}
          <li><a href="{{ url_for('backend.index') }}"><i class="fas fa-tools"></i> Manage (Admin Only)</a></li>
     {% endif %}
    <li><a href="{{ url_for('frontend.logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
  </ul>
</div>
        {% endif %}
      </ul>
    </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


{% block content %}

{% endblock %}

<script src="{{ url_for('static', filename='frontend/js/jquery-2.2.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='frontend/js/bootstrap.min.js') }}"></script>

</body>
</html>

application/frontend/templates/frontend/view.html
{% extends 'frontend/master.html' %}

{% block title %}
{{ part.partnum }} - NLMK PartManager
{% endblock %}


{% block content %}

<!-- Content area start -->
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                    <div class="heading text-center">
                        <h3>{{ part.partnum | upper }} {{ part.name | upper }}</h3>
                    </div>

                            <div class="well">
                                <form method="POST">
                                {{ form.csrf_token }}
                                <p>Available: {{ part.available_qty }}</p>
                                                            {% with messages = get_flashed_messages() %}
                                  {% if messages %}
                                    {% for message in messages %}
                                      <center><p style="color:red;">{{ message }}</p></center>
                                    {% endfor %}
                                  {% endif %}
                            {% endwith %}
                                <div class="form-group">
                                    {{ form.quantity(class="form-control", placeholder="Qty") }}
                                    {% for error in form.quantity.errors %}
                                        <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success btn-lg btn-block"><i class="fas fa-shopping-cart"></i> Checkout</button>
                                </div>                  
                                </form>
                            </div>



                </div>
                </div>
                <!-- Form content box end -->
            </div>
{% endblock %}